mini projet/Models/Produit.cs
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;
using System.Xml.Linq;

namespace mini_projet.Models
{
	public class Produit
	{
        public int ProduitId { get; set; }
		[Required]
        [Display(Name = "Name")]
        [StringLength(50, MinimumLength = 2)]
		public string Nom { get; set; }
		[Required]
		[Display(Name = "Price in Dinars")]
		public float Prix { get; set; }
		
		[Display(Name = "Category")]
		public int CategorieId{ get; set; }
        [Display(Name = "Category")]
        public Categorie Categorie { get; set; }
		[Required]
		[Display(Name = "Quantity in unit")]
		public int Quantite { get; set; }
		[Required]
		[Display(Name = "Image")]
		public string Image { get; set; }
	}
}

mini projet/Controllers/PanierController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using mini_projet.Models.Help;
using mini_projet.Models.Repositories;
using mini_projet.Models;

namespace mini_projet.Controllers
{
    public class PanierController : Controller
    {
        readonly IProduitRepository produitRepository;
        public PanierController(IProduitRepository produitRepository)
        {
            this.produitRepository = produitRepository;
        }
        public ActionResult Index()
        {
            ViewBag.Liste = ListeCart.Instance.Items;
            ViewBag.total = ListeCart.Instance.GetSubTotal();
            return View();
        }
        public ActionResult AjouterProduit(int id)
        {
            Produit pp = produitRepository.GetById(id);
            ListeCart.Instance.AddItem(pp);
            ViewBag.Liste = ListeCart.Instance.Items;
            ViewBag.total = ListeCart.Instance.GetSubTotal();
            return View();
        }
      
        [HttpPost]
        public ActionResult PlusProduit(int id)
        {
            Produit pp = produitRepository.GetById(id);
            ListeCart.Instance.AddItem(pp);
            Item trouve = null;
            foreach (Item a in ListeCart.Instance.Items)
            {
                if (a.Prod.ProduitId == pp.ProduitId)
                    trouve = a;
            }
            var results = new
            {
                ct = 1,
                Total = ListeCart.Instance.GetSubTotal(),
                Quatite = trouve.quantite,
                TotalRow = trouve.TotalPrice
            };
            return Json(results);
        }
        public ActionResult CheckOut()
        {
            return View();
        }
        [HttpPost]
        public ActionResult CheckOut(FormCollection collection)
        {
            ListeCart.Instance.Items.Clear();
            ViewBag.Message = "Commande effectuée avec succès";
            return View();
        }
        [HttpPost]
        public ActionResult SupprimerProduit(int id)
        {
            Produit pp = produitRepository.GetById(id);
            ListeCart.Instance.RemoveItem(pp);
            var results = new
            {
                Total = ListeCart.Instance.GetSubTotal(),
            };
            return Json(results);
        }
    }
}

mini projet/Controllers/ProduitController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Hosting.Internal;
using mini_projet.Models;
using mini_projet.Models.Repositories;
using mini_projet.Models.ViewModels;
using NuGet.Protocol.Core.Types;
using static System.Runtime.InteropServices.JavaScript.JSType;
using System.Diagnostics;

namespace mini_projet.Controllers
{
	public class ProduitController : Controller
	{
		readonly IProduitRepository productRepository;
		readonly ICategorieRepository categorieRepository;
		private readonly IWebHostEnvironment hostingEnvironment;

		public ProduitController(IProduitRepository productRepository,ICategorieRepository categorieRepository, IWebHostEnvironment hostingEnvironment)
		{
			this.productRepository = productRepository;
			this.categorieRepository = categorieRepository;
			this.hostingEnvironment = hostingEnvironment;
		}
		// GET: ProduitController
		public ActionResult Index()
		{
            ViewBag.CategorieId = new SelectList(categorieRepository.GetAll(), "CategorieId", "Nom");
            var p = productRepository.GetAll();
			return View(p);
		}

		// GET: ProduitController/Details/5
		public ActionResult Details(int id)
		{
            ViewBag.CategorieId = new SelectList(categorieRepository.GetAll(), "CategorieId", "Nom");
            var p = productRepository.GetById(id);
			return View(p);
		}

		// GET: ProduitController/Create
		public ActionResult Create()
		{
			ViewBag.CategorieId = new SelectList(categorieRepository.GetAll(), "CategorieId", "Nom");
			return View();
		}

		// POST: ProduitController/Create
		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Create(CreateViewModelProd model)
		{
            ViewBag.CategorieId = new SelectList(categorieRepository.GetAll(), "CategorieId", "Nom");
          
			
            if (ModelState.IsValid)
			{
				string uniqueFileName = null;
				if (model.Image != null)
				{

					string uploadsFolder = Path.Combine(hostingEnvironment.WebRootPath, "images");

					uniqueFileName = Guid.NewGuid().ToString() + "_" + model.Image.FileName;
					string filePath = Path.Combine(uploadsFolder, uniqueFileName);

					model.Image.CopyTo(new FileStream(filePath, FileMode.Create));
				}
                Produit p = new Produit
				{
					Nom = model.Nom,
					Prix = model.Prix,
					CategorieId = model.CategorieId,
					Categorie = categorieRepository.GetById(model.CategorieId),
					Quantite = model.Quantite,
					Image = uniqueFileName
				};
				
                productRepository.Add(p);
                return RedirectToAction(nameof(Index));
            }
        

            return View();
        }

		// GET: ProduitController/Edit/5
		public ActionResult Edit(int id)
		{
			Produit product = productRepository.GetById(id);
            ViewBag.CategorieId = new SelectList(categorieRepository.GetAll(), "CategorieId", "Nom");
            EditViewModelProd productEditViewModel = new EditViewModelProd
			{
				ProduitId = product.ProduitId,
				Nom = product.Nom,
				Prix = product.Prix,
				CategorieId = product.CategorieId,
				Quantite = product.Quantite,
				ExistingImagePath = product.Image
			};
			return View(productEditViewModel);
		}
            // POST: ProduitController/Edit/5
            [HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Edit(EditViewModelProd model)
        {
			   ViewBag.CategorieId = new SelectList(categorieRepository.GetAll(), "CategorieId", "Nom");
            try
			{ 
                if (ModelState.IsValid)
                {
              
                    Produit product = productRepository.GetById(model.ProduitId);

					product.Nom = model.Nom;
					product.Prix = model.Prix;
					product.CategorieId = model.CategorieId;
					product.Quantite = model.Quantite;
                 
                    if (model.Image != null)
                    {
                        
                        if (model.ExistingImagePath != null)
                        {
                            string filePath = Path.Combine(hostingEnvironment.WebRootPath, "images", model.ExistingImagePath);
                            System.IO.File.Delete(filePath);
                        }
                     
                        product.Image = ProcessUploadedFile(model);
                    }
                   
                    Produit updatedProduct = productRepository.Edit(product);
                    if (updatedProduct != null)
                        return RedirectToAction("Index");
                    else
                        return NotFound();
                }
                return View(model);
            }
            catch
            {
                return View();
            }

        }

		// GET: ProduitController/Delete/5
		public ActionResult Delete(int id)
		{
			return View();
		}

		// POST: ProduitController/Delete/5
		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Delete(int id,Produit p)
		{
			try
			{
				p.ProduitId=id;
				productRepository.Delete(p);
				return RedirectToAction(nameof(Index));
			}
			catch
			{
				return View();
			}
		}
        private string ProcessUploadedFile(EditViewModelProd model)
        {
            string uniqueFileName = null;
            if (model.Image != null)
            {
                string uploadsFolder = Path.Combine(hostingEnvironment.WebRootPath, "images");
                uniqueFileName = Guid.NewGuid().ToString() + "_" + model.Image.FileName;
                string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    model.Image.CopyTo(fileStream);
                }
            }
            return uniqueFileName;
        }
    }
}

mini projet/Views/Produit/Create.cshtml
@model mini_projet.Models.ViewModels.CreateViewModelProd

@{
    ViewData["Title"] = "Create";
}

<h2 class="text-center text-secondary mt-4">Create Product</h2>


<hr />
<div class="row">
    <div class="col-md-4">
        <form enctype="multipart/form-data" asp-action="Create" class="ms-5">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group mb-3">
                <label asp-for="Nom" class="control-label mb-2"></label>
                <input asp-for="Nom" class="form-control" />
                <span asp-validation-for="Nom" class="text-danger"></span>
            </div>
            <div class="form-group mb-3">
                <label asp-for="Prix" class="control-label mb-2"></label>
                <input asp-for="Prix" class="form-control" />
                <span asp-validation-for="Prix" class="text-danger"></span>
            </div>
            <div class="form-group mb-3">
                <label asp-for="CategorieId" class="control-label mb-2"></label>
                <select asp-for="CategorieId" class ="form-control" asp-items="ViewBag.CategorieId"></select>
            </div>
            <div class="form-group mb-3">
                <label asp-for="Quantite" class="control-label mb-2"></label>
                <input asp-for="Quantite" class="form-control" />
                <span asp-validation-for="Quantite" class="text-danger"></span>
            </div>
            <div class="form-group row">
                <label asp-for="Image" class="col-sm-2 col-form-label"></label>
                <div class="col-sm-10">
                    <div class="custom-file">
                        <input asp-for="Image" class="form-control custom-file-input">
                        <label class="custom-file-label">Choose File...</label>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    <script>
        $(document).ready(function () {
            $('.custom-file-input').on("change", function () {
                var fileName = $(this).val().split("\\").pop();
                $(this).next('.custom-file-label').html(fileName);
            });
        });
    </script>
}

mini projet/Views/Produit/Delete.cshtml
@model mini_projet.Models.Produit

@{
    ViewData["Title"] = "Delete";
}

<h2 class="text-center text-secondary mt-4">Delete Product</h2>


<h3 class="ms-5">Are you sure you want to delete this?</h3>
<div>

  
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ProduitId" />
        <input type="submit" value="Delete" class="btn btn-danger ms-5" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

mini projet/Views/Produit/Details.cshtml
@model mini_projet.Models.Produit

@{
    ViewData["Title"] = "Details";
    var photo = "~/images/" + (Model.Image);
}

<h2 class="text-center text-secondary mt-4">Product details</h2>

<div>
    <dl class="row m-5">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nom)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nom)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Prix)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Prix)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Categorie)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Categorie.Nom)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Quantite)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Quantite)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Image)
        </dt>
        <dd class = "col-sm-10">
            <img src="@photo" asp-append-version="true" height="120" width="120" />
        </dd>
    </dl>
</div>
<div class="ms-5">
    <a asp-action="Edit" asp-route-id="@Model?.ProduitId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

mini projet/Views/Produit/Edit.cshtml
@model mini_projet.Models.ViewModels.EditViewModelProd

@{
    ViewData["Title"] = "Edit";
    var photoPath = "~/images/" + (Model.ExistingImagePath ?? "noimage.jpg");

}
<h2 class="text-center text-secondary mt-4">Edit Product</h2>

<div class="row">
    <div class="col-md-4">
        <form asp-controller="Produit" asp-action="Edit" enctype="multipart/form-data" method="post" class="m-5">
            <div asp-validation-summary="All" class="text-danger"></div>
            <input type="hidden" asp-for="ProduitId" />
            <input hidden asp-for="ProduitId" />
<input hidden asp-for="ExistingImagePath" />
            <div class="form-group mb-4">
                <label asp-for="Nom" class="control-label"></label>
                <input asp-for="Nom" class="form-control" />
                <span asp-validation-for="Nom" class="text-danger"></span>
            </div>
            <div class="form-group mb-4">
                <label asp-for="Prix" class="control-label"></label>
                <input asp-for="Prix" class="form-control" />
                <span asp-validation-for="Prix" class="text-danger"></span>
            </div>
            <div class="form-group mb-4">
                <label asp-for="CategorieId" class="control-label"></label>
                <select asp-for="CategorieId" class="form-control" asp-items="ViewBag.CategorieId"></select>
                <span asp-validation-for="CategorieId" class="text-danger"></span>
            </div>
            <div class="form-group mb-4" >
                <label asp-for="Quantite" class="control-label"></label>
                <input asp-for="Quantite" class="form-control" />
                <span asp-validation-for="Quantite" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Image" class="control-label"></label>
                <input asp-for="Image" class="form-control" />
          
            </div>
            <div class="form-group row col-sm-4 offset-4">
                <img class="mt-4" src="@photoPath" asp-append-version="true" height="120" width="120" />
            </div>
            <div class="form-group row">
                <div class="col-sm-10 mt-4">
                    <button type="submit" class="btn btn-primary">Update</button>
                    <a asp-action="index" asp-controller="Product" class="btn btn-primary">Cancel</a>
                </div>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" class="ms-5">Back to List</a>
</div>

@section Scripts {
            <script>
                $(document).ready(function () {
                    $('.custom-file-input').on("change", function () {
                        var fileName = $(this).val().split("\\").pop();
                        $(this).next('.custom-file-label').html(fileName);
                        $("#imageEmp").attr("src", "/" + fileName);
                    });
                });
            </script>
	}

mini projet/Views/Produit/Index.cshtml
    @model IEnumerable<mini_projet.Models.Produit>
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@{
    ViewData["Title"] = "Products";

}

<h2 class="text-center text-secondary mt-4">List of products</h2>
@if (SignInManager.IsSignedIn(User) && User.IsInRole("Admin"))
{
    <p>
        <a asp-action="Create" class="ms-4">Create new product</a>
    </p>
    <table class="table ms-3 text-center table-striped align-middle">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Nom)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Prix)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Categorie)

                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Quantite)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Image)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr class="text-center">
                    <td>
                        @Html.DisplayFor(modelItem => item.Nom)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Prix)
                    </td>
                    <td>

                        @Html.DisplayFor(modelItem => item.Categorie.Nom)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Quantite)
                    </td>
                    <td>
                        <img src="~/images/@item.Image" alt="Product Image" width="100" height="100" />
                    </td>
                    <td>
                        <a asp-action="Edit" asp-route-id="@item.ProduitId">Edit<img class="actionimg" src="~/images/editing.png"/></a> |
                        <a asp-action="Details" asp-route-id="@item.ProduitId">View<img class="actionimg" src="~/images/sight.png" /></a> |
                        <a asp-action="Delete" asp-route-id="@item.ProduitId">Delete<img class="actionimg" src="~/images/delete.png" /></a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
else {
        <div class="card-group">
        @foreach (var product in Model)
        {
        var photoPath = "~/images/" + (product.Image ?? "noimage.jpg");
        <div class="card m-3 ms-5 text-center" style="min-width: 18rem; max-width:20%;">
        <div class="card-header">
        <h5><b>Désignation : </b> @product.Nom</h5>
        <h5><b>Prix : </b>@product.Prix</h5>
        <h5><b>Quantité : </b> @product.Quantite</h5>
        <h5><b>Quantité : </b> @product.Categorie.Nom</h5>
        </div>
        <img class="card-img-top imageThumbnail h-75 w-100" src="@photoPath" asp-append-version="true" />
        <div class="card-footer text-center">
                    @if (SignInManager.IsSignedIn(User))
                    {
                        @Html.ActionLink("Ajouter au panier »", "AjouterProduit", "Panier", new { id = @product.ProduitId }, "")
                    }
        </div>
        </div>
        }
    </div>
}